---
- hosts: test
  become: true

  tasks:
  - name: Add the user3
    ansible.builtin.user:
      name: user3
      comment: user3forsf
      generate_ssh_key: yes
  - name: CopySShHkey
    ansible.builtin.shell: ssh-copy-id -i /home/user3/.ssh/id_rsa.pub root@192.168.88.132